FROM ubuntu:20.04

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qqy && \
    apt-get install magic-wormhole -y && \
    apt-get autoremove -y \
    rm -rf /var/lib/apt/lists/*
    
ENV DEBIAN_FRONTEND
