FROM ubuntu:20.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -qqy && \
    DEBIAN_FRONTEND=noninteractive apt-get install magic-wormhole sed -qqy && \
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -qqy \
    rm -rf /var/lib/apt/*

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 
