FROM kalilinux/kali-linux-docker:latest
MAINTAINER danilonc

RUN apt-get update -y &&\
    apt-get dist-upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get install -y command-not-found metasploit-framework python-ipython tmux python-pip python3-pip build-essential spike python-z3

RUN pip install pwntools