FROM ubuntu:latest
MAINTAINER danilonc

# Update Kali
RUN apt-get update -y && apt-get dist-upgrade -y && apt-get autoremove -y

# Install Tools
RUN apt-get update -y && apt-get dist-upgrade -y && apt-get install build-essential git cmake python3-dev python3-setuptools python-ipython tmux python3-pip python3-colorama python3-termcolor python3-terminaltables python3-pygments -y

# Install shellen 
RUN pip3 install shellen

# Default command
CMD /bin/bash
