FROM kalilinux/kali-linux-docker:latest
MAINTAINER danilonc

RUN apt-get update -y && apt-get dist-upgrade -y && apt-get install metasploit-framework python-ipython tmux -y
RUN /etc/init.d/postgresql start && msfdb init && /etc/init.d/postgresql stop

CMD msfdb start && bash
